# Generated by Django 5.1.3 on 2024-11-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoneworkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonedetails',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
